# Generated by Django 4.2.8 on 2024-05-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('poster_path', models.CharField(max_length=200)),
                ('popularity', models.FloatField()),
                ('adult', models.BooleanField()),
                ('release_date', models.DateField()),
                ('is_latest', models.BooleanField()),
                ('is_popular', models.BooleanField()),
                ('genre_ids', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
    ]
